
# Lock-screen layout and authentication widgets.

$bin = ~/.config/hypr/bin

general {
    ignore_empty_input = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 30
    outline_thickness = 0
    dots_size = 0.55
    dots_spacing = 0.55
    outer_color = rgba(242, 243, 244, 0)
    inner_color = rgba(242, 243, 244, 0)
    font_color = rgba(242, 243, 244, 0.75)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    check_color = rgba(204, 136, 34, 0)
    fail_color = rgba(204, 34, 34, 1)
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    position = 0, -633
    halign = center
    valign = center
    font_family = SF Pro Display
}

label {
    monitor =
    text = cmd[update:2000] echo "$($bin/player)"
    color = rgba(242, 243, 244, 0.75)
    font_size = 22
    font_family = SF Pro Display, JetBrainsMono Nerd Font Propo
    position = 20, -10
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:3000] echo "<span>$($bin/network)</span>"
    font_size = 26
    font_family = JetBrainsMono Nerd Font Propo
    position = -50, -10
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:5000] echo "<span>$($bin/battery)</span>"
    color = rgba(242, 243, 244, 0.75)
    font_size = 26
    font_family = JetBrainsMono Nerd Font Propo
    position = -100, -10
    halign = right
    valign = top
}

label {
    monitor =
    text = <span font_weight="bold">$LAYOUT</span>
    color = rgba(242, 243, 244, 0.75)
    font_size = 24
    font_family = SF Pro Display
    position = -180, -12
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] echo "<span font_weight='bold'>$(date '+%A, %B %d')</span>"
    color = rgba(242, 243, 244, 0.75)
    font_size = 42
    font_family = SF Pro Display
    position = 0, 635
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span font_weight='bold'>$(date '+%k:%M')</span>"
    color = rgba(242, 243, 244, 0.75)
    font_size = 138
    font_family = SF Pro Display
    position = 0, 510
    halign = center
    valign = center
}

label {
    monitor =
    text = <span font_weight="bold">Aditya Chaudhary</span>
    color = rgba(242, 243, 244, 0.75)
    font_size = 28
    font_family = SF Pro Display
    position = 0, -522
    halign = center
    valign = center
}

label {
    monitor =
    text = Touch ID or Enter Password
    color = rgba(242, 243, 244, 0.75)
    font_size = 16
    font_family = SF Pro Display
    position = 0, -567
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/Pictures/profile.jpg 
    border_size = 0
    size = 200
    rounding = -1
    position = 0, -353
    halign = center
    valign = center
}
